export const UPDATE_SHOP_LIST = "UPDATE_SHOP_LIST"
export const SHOW_ADD = "SHOW_ADD"
export const CLOSE_ADD = "CLOSE_ADD"
export const SHOW_EDIT = "SHOW_EDIT"
export const CLOSE_EDIT = "CLOSE_EDIT"
export const FILTER_SHOPS = "FILTER_SHOPS"
export const SHOW_FILTER = "SHOW_FILTER"
export const CLOSE_FILTER = "CLOSE_FILTER"
